title: Wanting Mao   （毛婉婷） # your name (or website title) here
logo: "img/my_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior at UC San Diego majoring in
  <b>Data Science</b> and <b>Mathematics(Applied)</b>.
  <br>
  Email: wamao@ucsd.edu 
  <br>
  Phone Number: (858)267-7026
  <br><br>
  <a href="https://www.linkedin.com/in/wanting-mao-351a22238/">View My LinkedIn Profile</a>
  <a href="">
  
theme: jekyll-theme-minimal
