title: > 
  <br>Wanting Mao<br>
  <br>毛婉婷<br> 
logo: "img/my_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior at UC San Diego majoring in
  <br><b>Data Science</b> and <b>Mathematics(Applied)</b>.<br>
  <br>
  Email: wamao@ucsd.edu 
  <br><br>
  <a href="https://www.linkedin.com/in/wanting-mao-351a22238/">View My LinkedIn Profile</a>
  <a href="">
  <a href = "https://docs.google.com/document/d/1tHoMRRbEzGBDa49JPkJmIpScprbj5nrc/edit?usp=sharing&ouid=104055694262069304107&rtpof=true&sd=true">View My Reseme</a>
  
theme: jekyll-theme-minimal
