title: >
  <br>Wanting Mao<br>
  <br>毛婉婷<br> 
logo: "img/my_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior at UC San Diego majoring in
  <br><b>Data Science</b> and <b>Mathematics(Applied)</b>.<br>
  <br>
  Email: wamao@ucsd.edu 
  <br>
  <br>
  <a href = "https://drive.google.com/file/d/1CLliHVyqYhYBxsJ2UeUNhDpr5hEB-8bo/view?usp=sharing">View My CV</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/wanting-mao-351a22238/">View My LinkedIn Profile</a>
  <br>
  <a href="">
  
theme: jekyll-theme-minimal
